package tools.muthuishere.spinx.kamal;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Generates a ready-to-use Kamal deployment spec (YAML) for VPS deployments.
 *
 * <p>The generated spec includes:
 * <ul>
 *   <li>PostgreSQL 16 as the primary database accessory</li>
 *   <li>Redis 7 (cache) as the session/cache-store accessory</li>
 *   <li>Redis 7 (queue) as the dedicated job-queue accessory (port 6380)</li>
 *   <li>Custom {@code storagePath} for all persistent data volumes</li>
 *   <li>Secret-manager integration via {@code secretsFile}</li>
 * </ul>
 *
 * <p>Invoke via the CLI:
 * <pre>
 *   spinx kamal generate-spec ./kamalconfig.yaml
 * </pre>
 */
public class KamalSpecGenerator {

    private KamalSpecGenerator() {}

    /**
     * Writes a comprehensive Kamal deployment spec template to the given path.
     *
     * @param outputPath file path to write the generated YAML to
     */
    public static void generate(String outputPath) {
        Path out = Paths.get(outputPath).toAbsolutePath().normalize();
        String yaml = buildSpec();

        try (FileWriter writer = new FileWriter(out.toFile(), StandardCharsets.UTF_8)) {
            writer.write(yaml);
            System.out.println("✅ Generated Kamal spec at: " + out);
            System.out.println();
            System.out.println("📋 Next steps:");
            System.out.println("  1. Replace placeholder values (YOUR_VPS_IP, YOUR_GITHUB_USERNAME, etc.)");
            System.out.println("     in: " + out);
            System.out.println("  2. Create .env.secrets.prod with your secret values — add it to .gitignore!");
            System.out.println("  3. Ensure the storagePath directory exists on the VPS:");
            System.out.println("     ssh deploy@YOUR_VPS_IP 'mkdir -p /data/myapp'");
            System.out.println("  4. Run:  spinx kamal setup  -c " + out);
            System.out.println("  5. Run:  spinx kamal deploy -c " + out);
        } catch (IOException e) {
            throw new RuntimeException("Failed to write spec to " + out, e);
        }
    }

    /** Returns the YAML template string. */
    static String buildSpec() {
        return
"# =============================================================================\n" +
"# Kamal deployment spec — generated by Spinx\n" +
"# Includes: PostgreSQL 16, Redis 7 (cache), Redis 7 (queue),\n" +
"#           custom storage paths, and secret-manager integration.\n" +
"# =============================================================================\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Service identity\n" +
"# ---------------------------------------------------------------------------\n" +
"serviceName: \"myapp\"\n" +
"image: \"myorg/myapp\"          # Docker Hub: \"user/image\"  |  GHCR: \"ghcr.io/org/image\"\n" +
"dockerfilePath: \"Dockerfile\"\n" +
"environmentFile: \".env\"\n" +
"containerPort: 3000\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Custom storage path\n" +
"# All accessory data volumes are rooted here when no explicit volume is set.\n" +
"# Ensure this directory exists on the VPS before the first deploy:\n" +
"#   ssh deploy@YOUR_VPS_IP 'mkdir -p /data/myapp'\n" +
"# ---------------------------------------------------------------------------\n" +
"storagePath: \"/data/myapp\"\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Secret manager — secretsFile\n" +
"# File format: KEY=value (same as .env — one entry per line, # for comments).\n" +
"# Add to .gitignore so it is NEVER committed to source control!\n" +
"# Key names are written to deploy.yml `secrets:`; values are NEVER logged.\n" +
"# ---------------------------------------------------------------------------\n" +
"secretsFile: \".env.secrets.prod\"\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Target VPS servers (SSH-reachable IPs or hostnames)\n" +
"# ---------------------------------------------------------------------------\n" +
"servers:\n" +
"  - \"YOUR_VPS_IP\"\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Container registry\n" +
"# ---------------------------------------------------------------------------\n" +
"registry:\n" +
"  server: \"ghcr.io\"              # Remove this line to use Docker Hub\n" +
"  username: \"YOUR_GITHUB_USERNAME\"\n" +
"  passwordEnvVar: \"KAMAL_REGISTRY_PASSWORD\"  # Name of env-var holding the token\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# SSH settings\n" +
"# ---------------------------------------------------------------------------\n" +
"sshUser: \"deploy\"               # SSH user on the VPS (must have Docker access)\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Application secrets — names only; values come from secretsFile or env\n" +
"# ---------------------------------------------------------------------------\n" +
"secrets:\n" +
"  - SECRET_KEY_BASE\n" +
"  - DATABASE_URL\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Application environment variables (visible in deploy.yml — no secrets here)\n" +
"# ---------------------------------------------------------------------------\n" +
"environmentVariables:\n" +
"  RAILS_ENV: \"production\"\n" +
"  REDIS_URL: \"redis://redis:6379/0\"        # Cache / session store\n" +
"  QUEUE_REDIS_URL: \"redis://queue:6380/0\"  # Job queue (Sidekiq / BullMQ / etc.)\n" +
"\n" +
"# ---------------------------------------------------------------------------\n" +
"# Accessory services (PostgreSQL, Redis cache, Redis queue)\n" +
"# Each service is managed by Kamal on the same VPS alongside the app.\n" +
"# ---------------------------------------------------------------------------\n" +
"accessories:\n" +
"\n" +
"  # PostgreSQL 16 — primary database\n" +
"  postgres:\n" +
"    image: \"postgres:16\"\n" +
"    host: \"YOUR_VPS_IP\"\n" +
"    port: 5432\n" +
"    secrets:\n" +
"      - POSTGRES_PASSWORD\n" +
"    env:\n" +
"      POSTGRES_USER: \"myapp\"\n" +
"      POSTGRES_DB: \"myapp_production\"\n" +
"    volumes:\n" +
"      - \"/data/myapp/postgres:/var/lib/postgresql/data\"\n" +
"\n" +
"  # Redis 7 — cache and session store\n" +
"  redis:\n" +
"    image: \"redis:7.2-alpine\"\n" +
"    host: \"YOUR_VPS_IP\"\n" +
"    port: 6379\n" +
"    volumes:\n" +
"      - \"/data/myapp/redis:/data\"\n" +
"\n" +
"  # Redis 7 — job queue (Sidekiq / BullMQ / etc.)\n" +
"  # Runs on port 6380 to keep queue traffic isolated from cache traffic.\n" +
"  queue:\n" +
"    image: \"redis:7.2-alpine\"\n" +
"    host: \"YOUR_VPS_IP\"\n" +
"    port: 6380\n" +
"    volumes:\n" +
"      - \"/data/myapp/queue:/data\"\n" +
"    env:\n" +
"      MAXMEMORY_POLICY: \"noeviction\"\n";
    }
}
