package tools.muthuishere.spinx.gcp.cloudrun;

import com.fasterxml.jackson.annotation.JsonIgnore;
import tools.muthuishere.spinx.SpinxBaseConfig;
import java.util.HashMap;

public class GcpCloudRunConfig extends SpinxBaseConfig {
    
    // GCP-specific Configuration
    private String projectId;
    private String region;
    
    // Resource Configuration
    private String cpu;
    private String memory;
    private int minInstances;
    private int maxInstances;
    private int concurrency;
    private int timeout;
    
    // Access Configuration
    private boolean allowUnauthenticated;
    
    // Constructor
    public GcpCloudRunConfig() {
        this.region = "us-central1";
        setDockerfilePath("Dockerfile");
        setEnvironmentFile(".env");
        setContainerPort(8080);
        this.cpu = "1";
        this.memory = "512Mi";
        this.minInstances = 0;
        this.maxInstances = 10;
        this.concurrency = 80;
        this.timeout = 300;
        this.allowUnauthenticated = true;
        setEnvironmentVariables(new HashMap<>());
    }
    
    // Computed getters for derived names
    @JsonIgnore
    public String getArtifactRegistryRepository() {
        return getServiceName().toLowerCase().replace("_", "-");
    }
    
    @JsonIgnore
    public String getImageUri() {
        return region + "-docker.pkg.dev/" + projectId + "/" + getArtifactRegistryRepository() + "/" + getServiceName().toLowerCase();
    }
    
    @JsonIgnore
    public String getServiceUrl() {
        return "https://" + getServiceName().toLowerCase() + "-" + getRandomHash() + "-" + region + ".a.run.app";
    }
    
    private String getRandomHash() {
        // This would be generated by Google Cloud Run
        return "xxxxxxxx";
    }
    
    // Getters and Setters
    public String getProjectId() {
        return projectId;
    }
    
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }
    
    public String getRegion() {
        return region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    
    public String getCpu() {
        return cpu;
    }
    
    public void setCpu(String cpu) {
        this.cpu = cpu;
    }
    
    public String getMemory() {
        return memory;
    }
    
    public void setMemory(String memory) {
        this.memory = memory;
    }
    
    public int getMinInstances() {
        return minInstances;
    }
    
    public void setMinInstances(int minInstances) {
        this.minInstances = minInstances;
    }
    
    public int getMaxInstances() {
        return maxInstances;
    }
    
    public void setMaxInstances(int maxInstances) {
        this.maxInstances = maxInstances;
    }
    
    public int getConcurrency() {
        return concurrency;
    }
    
    public void setConcurrency(int concurrency) {
        this.concurrency = concurrency;
    }
    
    public int getTimeout() {
        return timeout;
    }
    
    public void setTimeout(int timeout) {
        this.timeout = timeout;
    }
    
    public boolean isAllowUnauthenticated() {
        return allowUnauthenticated;
    }
    
    public void setAllowUnauthenticated(boolean allowUnauthenticated) {
        this.allowUnauthenticated = allowUnauthenticated;
    }
}
